### PR TITLE
Fixup zsh completion

### PR DESCRIPTION
**Pull request by esc**
A few minor updates and cleanups for the zsh completion.

### CODE REVIEW

**Comment by mriehl** [comment]
@esc I just released this. But it doesn't seem to be working on my machine anymore. I am investigating.

**Comment by mriehl** [comment]
All's fine. It works like a charm. I just ran into the bug that there are no completions if `pyb -Qt` fails (which is the case if you don't have a `build.py` yet). But this bug has always been there. I'll look into fixing it, but this shouldn't belittle your changes ;-)

Thanks a lot.

**Comment by esc** [comment]
How do you want it to behave?

On 11 February 2016 15:52:23 CET, Maximilien Riehl notifications@github.com wrote:

> All's fine. It works like a charm. I just ran into the bug that there
> are no completions if `pyb -Qt` fails (which is the case if you don't
> have a `build.py` yet). But this bug has always been there. I'll look
> into fixing it, but this shouldn't belittle your changes ;-)
> 
> Thanks a lot.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pybuilder/pybuilder-completions/pull/1#issuecomment-182895871

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mriehl** [comment]
Basically everything but the tasks should work. At the very least, I want `--start-project`, `--help` and `-v/-X` to complete.

**Comment by mriehl** [comment]
Some of the options like task exclusion (which is actually also missing) would not make sense without a build.py

**Comment by esc** [comment]
Okay, let me see what I can craft, I made two pretty solid zsh completions in the last year, maybe I can apply some of the lessons here.

**Pull request merged**
